import Head from 'next/head'
import Features from '../components/Features';
import Main from "../components/Main";
import Value from '../components/Value';
import ViewList from '../components/ViewList';
import React, { Fragment } from 'react'
import useGetSinglePost from '../config/hooks/useGetSinglePost';
import useGetPostCategories from '../config/hooks/useGetPostCategories';




export default function Home() {
  const { data } = useGetPostCategories()
  return (
    <div  >
      <Fragment>
        <Head>
          <title>FieldMaxPro - Field Force Automation</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Main />
        <Features />
        <Value />
        <ViewList />
      </Fragment>
    </div>
  )
}
